### ISSUE TITLE
rsa_epochs on single sensor without spatial searchlight

### ISSUE THREAD

**Issue by AlexLepauvre** [wmvanvliet/mne-rsa#13]
Hi!

I am currently trying to analyze some data of mine using the mne_rsa package. I am analyzing iEEG data and therefore, we are mainly doing single sensor analysis at the moment, without spatial searchlight that is.

In order to understand how to do so, I have played around with the tutorial found here: https://users.aalto.fi/~vanvlm1/mne-rsa/auto_examples/plot_sensor_level.html#sphx-glr-auto-examples-plot-sensor-level-py

I have noticed that when setting the spatial_radius to None, as described in the API documentation, like here:
´´´
rsa_result = mne_rsa.rsa_epochs(
    epochs,                           # The EEG data
    dsm_vis,                          # The model DSM
    epochs_dsm_metric='sqeuclidean',  # Metric to compute the EEG DSMs
    rsa_metric='kendall-tau-a',       # Metric to compare model and EEG DSMs
    spatial_radius=45,                # Spatial radius of the searchlight patch
    temporal_radius=0.05,             # Temporal radius of the searchlight path
    tmin=0.15, tmax=0.25,             # To save time, only analyze this time interval
    n_jobs=1,                         # Only use one CPU core. Increase this for more speed.
    n_folds=None,
    verbose=False
    picks="Fz")                    # Set to True to display a progress bar
´´´

I get the  error:
´´´
Traceback (most recent call last):
  File "C:\Users\alexander.lepauvre\Anaconda3\envs\mne\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-e87dfff10dfc>", line 1, in <module>
    rsa_result = mne_rsa.rsa_epochs(
  File "C:\Users\alexander.lepauvre\Anaconda3\envs\mne\lib\site-packages\mne_rsa\sensor_level.py", line 380, in rsa_epochs
    return mne.EvokedArray(data, info, tmin, comment='RSA',
  File "<decorator-gen-203>", line 24, in __init__
  File "C:\Users\alexander.lepauvre\Anaconda3\envs\mne\lib\site-packages\mne\evoked.py", line 856, in __init__
    raise ValueError('Data must be a 2D array of shape (n_channels, '
ValueError: Data must be a 2D array of shape (n_channels, n_samples), got shape (12,)
´´´
I am guessing that this is not the intended behavior right? I have tried to look at the code, as the error mentions this lies in the data being fed into the evoked ,mne function has wrong dimensions, but I wasn't able to fix it. I have however noticed that when replacing the None by a zero it works, though I am not sure the same happens as with None.

### How to reproduce:
import mne
import mne_rsa

data_path = mne.datasets.kiloword.data_path(verbose=True)
epochs = mne.read_epochs(data_path + '/kword_metadata-epo.fif')
epochs = epochs.resample(100)

epochs.metadata.sample(10)

dsm_vis = mne_rsa.compute_dsm(epochs.metadata[['NumberOfLetters']],
                              metric='euclidean')
mne_rsa.plot_dsms(dsm_vis)

rsa_result = mne_rsa.rsa_epochs(
    epochs,                           # The EEG data
    dsm_vis,                          # The model DSM
    epochs_dsm_metric='sqeuclidean',  # Metric to compute the EEG DSMs
    rsa_metric='kendall-tau-a',       # Metric to compare model and EEG DSMs
    spatial_radius=None,                # Spatial radius of the searchlight patch
    temporal_radius=0.05,             # Temporal radius of the searchlight path
    tmin=0.15, tmax=0.25,             # To save time, only analyze this time interval
    n_jobs=1,                         # Only use one CPU core. Increase this for more speed.
    n_folds=None,
    verbose=False)                    # Set to True to display a progress bar

Thanks in advances for your help,

Kind regards,

Alex

**Comment by wmvanvliet** [comment]
Thanks @AlexLepauvre for the detailed bug report. Sorry I didn't get to it sooner.
